# Quick `ms3` reference

## To run this notebook

* install ms3 (`pip install ms3`)
* set the `DATA_PATH` to where you want the folder `dcml_corpora` to be created that contains the data

Read about {ref}`keys_and_ids` {ref}`Keys and IDs <keys_and_ids>`

In [1]:
DATA_PATH = '~'

## Setup

In [2]:
import os
import ms3
from git import Repo

corpora_path = os.path.join(os.path.expanduser(DATA_PATH), 'dcml_corpora')
if os.path.isdir(corpora_path):
    repo = Repo(corpora_path)
else:
    repo = Repo.clone_from(url='https://github.com/DCMLab/dcml_corpora.git', 
                to_path=corpora_path, 
                multi_options=['--recurse-submodules', '--shallow-submodules'])
print(f"dcml_corpora @ commit {repo.commit().hexsha}")

dcml_corpora @ commit 9dcde40cba36d31b900ff12852cc557b8cca8221

## Parsing multiple scores at once

### The Corpus object

Scores often come grouped into a corpus, so when we want to parse multiple scores, we create a [Corpus](Corpus) object and pass it the directory containing the scores. `ms3` will scan the directory and discover all scores and TSV files that can be potentially parsed:

In [19]:
tchaikovsky_path = os.path.join(corpora_path, 'tchaikovsky_seasons')
corpus = ms3.Corpus(tchaikovsky_path)
corpus

[default|all]
Corpus 'tchaikovsky_seasons'
----------------------------
Location: /home/hentsche/dcml_corpora/tchaikovsky_seasons
View: This view is called 'default'. It
	- excludes fnames that are not contained in the metadata,
	- filters out file extensions requiring conversion (such as .xml), and
	- excludes review files and folders.

All 12 pieces are listed in 'metadata.tsv':

          scores measures    notes expanded   events   chords
        detected detected detected detected detected detected
op37a01        1        1        1        1        1        1
op37a02        1        1        1        1        1        1
op37a03        1        1        1        1        1        1
op37a04        1        1        1        1        1        1
op37a05        1        1        1        1        1        1
op37a06        1        1        1        1        1        1
op37a07        1        1        1        1        1        1
op37a08        1        1        1        1        1        1
op37a09        1        1        1        1        1        1
op37a10        1        1        1        1        1        1
op37a11        1        1        1        1        1        1
op37a12        1        1        1        1        1        1
24/96 files are excluded from this view.

24 files have been excluded based on their subdir.

When inspecting this object,

In [21]:
corpora_path = '~/corelli'
corpora = ms3.Parse(corpora_path, level='c')
corpora

[default|all]
All corpora
-----------
View: This view is called 'default'. It
	- excludes fnames that are not contained in the metadata,
	- filters out file extensions requiring conversion (such as .xml), and
	- excludes review files and folders.

             has   active   scores measures    notes expanded
        metadata     view detected detected detected detected
corpus
corelli      yes  default      149      149      149      149

452/1197 files are excluded from this view.

447 files have been excluded based on their subdir.
5 files have been excluded based on their file name.

**From here we can use the methods**

* [parse_scores()](Parse.parse_scores()) to parse all detected scores,
* [parse_tsv()](Parse.parse_tsv()) to parse all detected TSV files (previously extracted from scores),
* [parse()](Parse.parse()) to parse everything.

In [11]:
corpora.parse_scores()
corpora

[gunthamund|default|all]
All corpora
-----------
View: This view is called 'gunthamund'. It
	- filters out file extensions requiring conversion (such as .xml), and
	- excludes review files and folders.

               has      active   scores        measures    notes   labels expanded   events
          metadata        view detected parsed detected detected detected detected detected
corpus
docs            no  gunthamund        4      4        0        0        0        0        0
new_tests       no  gunthamund        0      0        0        0        0        0        0
old_tests       no  gunthamund       10     10       21       21        8        4        7

4/93 files are excluded from this view.

4 files have been excluded based on their file name.


There are 3 orphans that could not be attributed to any of the respective corpus's fnames.

**Now we can extract the facets we need from the parsed scores, e.g. information on all measures from all scores:**

In [16]:
corpora.get_facet('measures')

                                 mc  mn quarterbeats  duration_qb  keysig  \
corpus    fname              i
docs      cujus              0    1   1            0          1.5      -3
                             1    2   2          3/2          1.5      -3
                             2    3   3            3          1.5      -3
                             3    4   4          9/2          1.5      -3
                             4    5   5            6          1.5      -3
...                              ..  ..          ...          ...     ...
old_tests stabat_03_coloured 21  22  22           84          4.0      -2
                             22  23  23           88          4.0      -2
                             23  24  24           92          4.0      -2
                             24  25  25           96          4.0      -2
                             25  26  26          100          4.0      -2

                                timesig act_dur mc_offset  numbering_offset  \
corpus    fname              i
docs      cujus              0      3/8     3/8         0              <NA>
                             1      3/8     3/8         0              <NA>
                             2      3/8     3/8         0              <NA>
                             3      3/8     3/8         0              <NA>
                             4      3/8     3/8         0              <NA>
...                                 ...     ...       ...               ...
old_tests stabat_03_coloured 21     4/4       1         0              <NA>
                             22     4/4       1         0              <NA>
                             23     4/4       1         0              <NA>
                             24     4/4       1         0              <NA>
                             25     4/4       1         0              <NA>

                                 dont_count barline breaks       repeats  \
corpus    fname              i
docs      cujus              0         <NA>     NaN    NaN  firstMeasure
                             1         <NA>     NaN    NaN          <NA>
                             2         <NA>     NaN    NaN          <NA>
                             3         <NA>     NaN    NaN          <NA>
                             4         <NA>     NaN    NaN          <NA>
...                                     ...     ...    ...           ...
old_tests stabat_03_coloured 21        <NA>     NaN   line          <NA>
                             22        <NA>     NaN    NaN          <NA>
                             23        <NA>     NaN    NaN          <NA>
                             24        <NA>     NaN    NaN          <NA>
                             25        <NA>     NaN    NaN   lastMeasure

                                  next quarterbeats_all_endings  volta  \
corpus    fname              i
docs      cujus              0    (2,)                      NaN   <NA>
                             1    (3,)                      NaN   <NA>
                             2    (4,)                      NaN   <NA>
                             3    (5,)                      NaN   <NA>
                             4    (6,)                      NaN   <NA>
...                                ...                      ...    ...
old_tests stabat_03_coloured 21  (23,)                      NaN   <NA>
                             22  (24,)                      NaN   <NA>
                             23  (25,)                      NaN   <NA>
                             24  (26,)                      NaN   <NA>
                             25  (-1,)                      NaN   <NA>

                                markers jump_bwd jump_fwd play_until
corpus    fname              i
docs      cujus              0      NaN      NaN      NaN        NaN
                             1      NaN      NaN      NaN        NaN
                             2      NaN      NaN      NaN        NaN
                             3      NaN      NaN      NaN        NaN
                             4      NaN      NaN      NaN        NaN
...                                 ...      ...      ...        ...
old_tests stabat_03_coloured 21     NaN      NaN      NaN        NaN
                             22     NaN      NaN      NaN        NaN
                             23     NaN      NaN      NaN        NaN
                             24     NaN      NaN      NaN        NaN
                             25     NaN      NaN      NaN        NaN

[773 rows x 20 columns]

**Or we iterate through the corpora and print information on the first 10 notes:**

In [13]:
for corpus_name, corpus_object in corpora:
    print(f"First ten measures of {corpus_name}:")
    display(corpus_object.get_facet('notes').iloc[:10])

First ten measures of docs:

               mc  mn quarterbeats  duration_qb mc_onset mn_onset timesig  \
fname notes_i
cujus 0         1   1            0          1.0        0        0     3/8
      1         1   1            0          1.0        0        0     3/8
      2         1   1            0          1.5        0        0     3/8
      3         1   1            0          0.5        0        0     3/8
      4         1   1          1/2          1.0      1/8      1/8     3/8
      5         1   1            1          0.5      1/4      1/4     3/8
      6         1   1            1          0.5      1/4      1/4     3/8
      7         2   2          3/2          1.0        0        0     3/8
      8         2   2          3/2          1.0        0        0     3/8
      9         2   2          3/2          1.5        0        0     3/8

               staff  voice duration gracenote nominal_duration scalar  tied  \
fname notes_i
cujus 0            3      1      1/4       NaN              1/4      1  <NA>
      1            2      2      1/4       NaN              1/4      1  <NA>
      2            2      3      3/8       NaN              1/4    3/2  <NA>
      3            2      1      1/8       NaN              1/8      1  <NA>
      4            2      1      1/4       NaN              1/4      1  <NA>
      5            3      1      1/8       NaN              1/8      1  <NA>
      6            2      2      1/8       NaN              1/8      1  <NA>
      7            3      2      1/4       NaN              1/4      1  <NA>
      8            3      1      1/4       NaN              1/4      1  <NA>
      9            2      2      3/8       NaN              1/4    3/2     1

               tpc  midi name  octave  chord_id
fname notes_i
cujus 0          0    48   C3       3         5
      1         -3    63  Eb4       4         2
      2          1    67   G4       4         4
      3          0    72   C5       5         0
      4          2    74   D5       5         1
      5          5    47   B2       2         6
      6          2    62   D4       4         3
      7          0    48   C3       3        12
      8          0    60   C4       4        10
      9          1    67   G4       4         9

First ten measures of new_tests:

Empty DataFrame
Columns: []
Index: []

First ten measures of old_tests:

                      mc mn quarterbeats  duration_qb mc_onset mn_onset  \
fname         notes_i
05_symph_fant 0        1  1            0          1.0        0        0
              1        1  1            0          1.0        0        0
              2        1  1            0          1.0        0        0
              3        1  1            0          1.0        0        0
              4        1  1            0          1.0        0        0
              5        1  1            0          1.0        0        0
              6        1  1            0          1.0        0        0
              7        1  1            0          1.0        0        0
              8        1  1            1          1.0      1/4      1/4
              9        1  1            1          1.0      1/4      1/4

                      timesig staff voice duration  ...    tremolo  \
fname         notes_i                               ...
05_symph_fant 0           4/4    28     1      1/4  ...  1/4_r32_0
              1           4/4    27     1      1/4  ...  1/4_r32_0
              2           4/4    26     1      1/4  ...  1/4_r32_0
              3           4/4    25     1      1/4  ...  1/4_r32_0
              4           4/4    24     1      1/4  ...  1/4_r32_0
              5           4/4    23     1      1/4  ...  1/4_r32_0
              6           4/4    22     1      1/4  ...  1/4_r32_0
              7           4/4    21     1      1/4  ...  1/4_r32_0
              8           4/4    28     1      1/4  ...  1/4_r32_0
              9           4/4    27     1      1/4  ...  1/4_r32_0

                      nominal_duration scalar  tied  tpc  midi  name octave  \
fname         notes_i
05_symph_fant 0                    1/4      1  <NA>   10    70   A#4      4
              1                    1/4      1  <NA>    7    73   C#5      5
              2                    1/4      1  <NA>    4    76    E5      5
              3                    1/4      1  <NA>    1    79    G5      5
              4                    1/4      1  <NA>   10    82   A#5      5
              5                    1/4      1  <NA>    7    85   C#6      6
              6                    1/4      1  <NA>    4    88    E6      6
              7                    1/4      1  <NA>    1    91    G6      6
              8                    1/4      1  <NA>   10    70   A#4      4
              9                    1/4      1  <NA>    7    73   C#5      5

                       chord_id volta
fname         notes_i
05_symph_fant 0              30  <NA>
              1              26  <NA>
              2              22  <NA>
              3              18  <NA>
              4              14  <NA>
              5              10  <NA>
              6               6  <NA>
              7               2  <NA>
              8              31  <NA>
              9              27  <NA>

[10 rows x 21 columns]

**The available facets are `'measures', 'notes', 'rests', 'notes_and_rests', 'labels', 'expanded', 'form_labels', 'cadences', 'events', 'chords'`.
We can request several at the same time:**

In [14]:
corpora.get_facets(['labels', 'chords'])

                                         mc  mn quarterbeats duration_qb  \
corpus    fname              facet  i
docs      cujus              labels 0     1   1            0         0.5
                                    1     1   1          1/2         0.5
                                    2     1   1            1         0.5
                                    3     2   2          3/2         0.5
                                    4     2   2            2         0.5
...                                      ..  ..          ...         ...
old_tests stabat_03_coloured chords 578  26  26          101         1.0
                                    579  26  26          100         1.0
                                    580  26  26          102         0.0
                                    581  26  26          100         1.0
                                    582  26  26          101         0.0

                                        mc_onset mn_onset timesig  staff  \
corpus    fname              facet  i
docs      cujus              labels 0          0        0     3/8      2
                                    1        1/8      1/8     3/8      2
                                    2        1/4      1/4     3/8      2
                                    3          0        0     3/8      2
                                    4        1/8      1/8     3/8      2
...                                          ...      ...     ...    ...
old_tests stabat_03_coloured chords 578      1/4      1/4     4/4      3
                                    579        0        0     4/4      4
                                    580      1/2      1/2     4/4      4
                                    581        0        0     4/4      4
                                    582      1/4      1/4     4/4      4

                                         voice harmony_layer  ... pedal  \
corpus    fname              facet  i                         ...
docs      cujus              labels 0        1             1  ...   NaN
                                    1        1             1  ...   NaN
                                    2        1             1  ...   NaN
                                    3        1             1  ...   NaN
                                    4        1             1  ...   NaN
...                                        ...           ...  ...   ...
old_tests stabat_03_coloured chords 578      1           NaN  ...   NaN
                                    579      1           NaN  ...   NaN
                                    580      1           NaN  ...   NaN
                                    581      2           NaN  ...   NaN
                                    582      2           NaN  ...   NaN

                                        Pedal_<sym>keyboardPedalPed</sym>  \
corpus    fname              facet  i
docs      cujus              labels 0                                 NaN
                                    1                                 NaN
                                    2                                 NaN
                                    3                                 NaN
                                    4                                 NaN
...                                                                   ...
old_tests stabat_03_coloured chords 578                               NaN
                                    579                               NaN
                                    580                               NaN
                                    581                               NaN
                                    582                               NaN

                                        volta Ottava:8va Ottava:15mb color  \
corpus    fname              facet  i
docs      cujus              labels 0    <NA>        NaN         NaN   NaN
                                    1    <NA>        NaN         NaN   NaN
                                    2    <NA>        NaN         NaN   NaN
                                    3    <NA>        NaN         NaN   NaN
                                    4    <NA>        NaN         NaN   NaN
...                                       ...        ...         ...   ...
old_tests stabat_03_coloured chords 578  <NA>        NaN         NaN   NaN
                                    579  <NA>        NaN         NaN   NaN
                                    580  <NA>        NaN         NaN   NaN
                                    581  <NA>        NaN         NaN   NaN
                                    582  <NA>        NaN         NaN   NaN

                                        color_a color_b  color_g color_r
corpus    fname              facet  i
docs      cujus              labels 0       NaN     NaN      NaN     NaN
                                    1       NaN     NaN      NaN     NaN
                                    2       NaN     NaN      NaN     NaN
                                    3       NaN     NaN      NaN     NaN
                                    4       NaN     NaN      NaN     NaN
...                                         ...     ...      ...     ...
old_tests stabat_03_coloured chords 578     NaN     NaN      NaN     NaN
                                    579     NaN     NaN      NaN     NaN
                                    580     NaN     NaN      NaN     NaN
                                    581     NaN     NaN      NaN     NaN
                                    582     NaN     NaN      NaN     NaN

[19586 rows x 41 columns]